services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:nightly
    container_name: calibre-web
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      #- configcalibre:/config
      #- torrents:/torrents
      - type: bind
        source: $HOST_MEDIA_PATH/books
        target: /books
      - type: bind
        source: $HOST_CONFIG_PATH/calibre
        target: /config
    networks:
      - internal

networks:
  internal:
    name: traefik-network
    external: true
