services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    restart: always
    volumes:
      #- torrents:/torrents
      #- configdeluge:/config
      #- downloads:/downloads
      - type: bind
        source: $HOST_MEDIA_PATH
        target: /torrents
      - type: bind
        source: $HOST_CONFIG_PATH/deluge
        target: /config  
    ports:
      - 8112:8112
      - 6688:6888
      - 6688:6688/udp
    environment:
      - DELUGE_LOGLEVEL=info
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - internal
      
networks:
  internal:
    name: traefik-network
    external: true
    