services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    restart: always
    volumes:
      #- torrents:/torrents
      #- configdeluge:/config
      #- downloads:/downloads
      - type: bind
        source: $HOST_MEDIA_PATH
        target: /torrents
      - type: bind
        source: $HOST_CONFIG_PATH/deluge
        target: /config  
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    networks:
      - internal
      
networks:
  internal:
    name: traefik-network
    external: true
    