services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # - configduplicati:/config
      # - backups:/backups
      # - config:/source
      - type: bind
        source: /mnt/data/data
        target: /data
      - type: bind
        source: /mnt/data/backups
        target: /backups
      - type: bind
        source: $HOST_CONFIG_PATH/duplicati
        target: /config
    networks:
      - internal
      
networks:
  internal:
    name: traefik-network
    external: true
# volumes:
#   configduplicati:
#     driver: local-persist
#     driver_opts:
#       mountpoint: $HOST_CONFIG_PATH/duplicati
#   backups:
#     driver: local-persist
#     driver_opts:
#       mountpoint: $HOST_CONFIG_PATH/backups