services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: always
#    network_mode: host
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:

    environment:
      #- PGID=${PGID}
      #- PUID=${PUID}
      - PGID=0
      - PUID=0
      - TZ=${TZ}
      - VERSION=latest
      - PLEX_CLAIM=claim-Hspz6weJgGMyWG3Nmwzw
    networks:
      - internal
      
networks:
  internal:
    name: traefik-network
    external: true
    