services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - --certificatesresolvers.le.acme.email=${ACME_MAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/seedbox/traefik:/etc/traefik:ro
      #- configtraefik:/config
      - type: bind
        source: $HOST_CONFIG_PATH/traefik
        target: /config
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - TZ=${TZ}
    networks:
      - internal
      
# Common network used by all services
networks:
  internal:
    name: "traefik-network"
        